/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "secondary-fixed-dim": "#c6bfff",
          "background": "#fff8f6",
          "on-tertiary": "#ffffff",
          "error": "#ba1a1a",
          "surface": "#fff8f6",
          "tertiary-fixed": "#77f7ec",
          "primary-fixed-dim": "#ffb598",
          "tertiary": "#006a64",
          "surface-container-highest": "#f0dfd9",
          "surface-variant": "#f0dfd9",
          "on-secondary-container": "#fffbff",
          "secondary-container": "#6f5fea",
          "on-secondary": "#ffffff",
          "surface-container-high": "#f6e5df",
          "on-surface": "#221a16",
          "on-primary-fixed": "#370e00",
          "secondary": "#5644d0",
          "on-tertiary-fixed": "#00201e",
          "inverse-primary": "#ffb598",
          "surface-dim": "#e8d6d1",
          "on-primary-fixed-variant": "#7a300c",
          "surface-container": "#fceae4",
          "on-primary": "#ffffff",
          "primary-fixed": "#ffdbce",
          "surface-container-low": "#fff1ec",
          "secondary-fixed": "#e4dfff",
          "primary-container": "#e8845a",
          "on-primary-container": "#622000",
          "on-error": "#ffffff",
          "on-tertiary-container": "#003d3a",
          "on-background": "#221a16",
          "surface-bright": "#fff8f6",
          "on-tertiary-fixed-variant": "#00504b",
          "inverse-surface": "#382e2a",
          "inverse-on-surface": "#ffede7",
          "tertiary-fixed-dim": "#57dad0",
          "outline": "#88726a",
          "primary": "#984622",
          "outline-variant": "#dbc1b8",
          "surface-tint": "#984622",
          "surface-container-lowest": "#ffffff",
          "on-secondary-fixed": "#160066",
          "on-surface-variant": "#55433c",
          "on-error-container": "#93000a",
          "error-container": "#ffdad6",
          "tertiary-container": "#18b1a8",
          "on-secondary-fixed-variant": "#4029ba"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px",
          "2xl": "1rem"
      },
      "spacing": {
          "sm": "16px",
          "lg": "40px",
          "xs": "8px",
          "base": "4px",
          "md": "24px",
          "xl": "64px",
          "gutter": "20px",
          "container-max": "1200px"
      },
      "fontFamily": {
          "sans": ["Inter", "sans-serif"],
          "heading": ["Be Vietnam Pro", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "headline-lg-mobile": ["Be Vietnam Pro", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "label-md": ["Inter", "sans-serif"],
          "display-lg": ["Be Vietnam Pro", "sans-serif"],
          "title-md": ["Be Vietnam Pro", "sans-serif"],
          "label-sm": ["Inter", "sans-serif"],
          "headline-lg": ["Be Vietnam Pro", "sans-serif"]
      },
      "fontSize": {
          "body-lg": ["20px", { "lineHeight": "32px", "fontWeight": "400" }],
          "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
          "body-md": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
          "label-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0.01em", "fontWeight": "500" }],
          "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
          "title-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
          "label-sm": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
          "headline-lg": ["40px", { "lineHeight": "48px", "fontWeight": "700" }]
      },
      boxShadow: {
          'sm': '0px 2px 4px rgba(45, 45, 45, 0.05)',
          'md': '0px 12px 24px rgba(45, 45, 45, 0.08)',
      }
    },
  },
  plugins: [],
}
