export const GIFT_TAXONOMY = [
  { name: 'Bracelet', type: 'Accessory' },
  { name: 'Customized Keychain', type: 'Accessory' },
  { name: 'Neck Chain', type: 'Accessory' },
  { name: 'Sunglasses', type: 'Accessory' },
  { name: 'Wallet', type: 'Accessory' },
  { name: 'Wrist Watch', type: 'Accessory' },
  { name: 'Fiction Novel', type: 'Book' },
  { name: 'Motivational Book', type: 'Book' },
  { name: 'Science Guide', type: 'Book' },
  { name: 'Self-help Book', type: 'Book' },
  { name: 'Bluetooth Earbuds', type: 'Electronics' },
  { name: 'Fitness Band', type: 'Electronics' },
  { name: 'Portable Speaker', type: 'Electronics' },
  { name: 'Smart Watch', type: 'Electronics' },
  { name: 'Cap', type: 'Fashion Item' },
  { name: 'Scarf', type: 'Fashion Item' },
  { name: 'Sling Bag', type: 'Fashion Item' },
  { name: 'Stylish T-shirt', type: 'Fashion Item' },
  { name: 'Beard Grooming Kit', type: 'Grooming Set' },
  { name: 'Perfume Set', type: 'Grooming Set' },
  { name: 'Skincare Kit', type: 'Grooming Set' },
  { name: 'Clay Art Pot', type: 'Handmade Craft' },
  { name: 'Handcrafted Candle', type: 'Handmade Craft' },
  { name: 'Handmade Greeting Card', type: 'Handmade Craft' },
  { name: 'Aroma Diffuser', type: 'Home Decor' },
  { name: 'LED Table Lamp', type: 'Home Decor' },
  { name: 'Mini Indoor Plant', type: 'Home Decor' },
  { name: 'Wall Art Frame', type: 'Home Decor' },
  { name: 'Customized Photo Frame', type: 'Personalized Gift' },
  { name: 'Engraved Pen', type: 'Personalized Gift' },
  { name: 'Name Printed Mug', type: 'Personalized Gift' },
  { name: 'LEGO Set', type: 'Toy' },
  { name: 'Puzzle Game', type: 'Toy' },
  { name: 'Remote Car', type: 'Toy' },
  { name: 'Soft Toy', type: 'Toy' },
];

export const GIFT_TYPE_LABELS = {
  Accessory: 'Phụ kiện',
  Book: 'Sách',
  Electronics: 'Đồ điện tử',
  'Fashion Item': 'Thời trang',
  'Grooming Set': 'Chăm sóc cá nhân',
  'Handmade Craft': 'Đồ thủ công',
  'Home Decor': 'Trang trí nhà cửa',
  'Personalized Gift': 'Quà cá nhân hóa',
  Toy: 'Đồ chơi',
};

export const GIFT_NAME_LABELS = {
  'Aroma Diffuser': 'Máy khuếch tán tinh dầu',
  'Beard Grooming Kit': 'Bộ chăm sóc râu',
  'Bluetooth Earbuds': 'Tai nghe Bluetooth',
  Bracelet: 'Vòng tay',
  Cap: 'Mũ lưỡi trai',
  'Clay Art Pot': 'Chậu gốm nghệ thuật',
  'Customized Keychain': 'Móc khóa cá nhân hóa',
  'Customized Photo Frame': 'Khung ảnh cá nhân hóa',
  'Engraved Pen': 'Bút khắc tên',
  'Fiction Novel': 'Tiểu thuyết',
  'Fitness Band': 'Vòng đeo tay thể thao',
  'Handcrafted Candle': 'Nến thủ công',
  'Handmade Greeting Card': 'Thiệp thủ công',
  'LED Table Lamp': 'Đèn bàn LED',
  'LEGO Set': 'Bộ LEGO',
  'Mini Indoor Plant': 'Cây cảnh mini',
  'Motivational Book': 'Sách truyền cảm hứng',
  'Name Printed Mug': 'Cốc in tên',
  'Neck Chain': 'Dây chuyền',
  'Perfume Set': 'Bộ nước hoa',
  'Portable Speaker': 'Loa di động',
  'Puzzle Game': 'Trò chơi xếp hình',
  'Remote Car': 'Xe điều khiển',
  Scarf: 'Khăn choàng',
  'Science Guide': 'Sách khoa học',
  'Self-help Book': 'Sách phát triển bản thân',
  'Skincare Kit': 'Bộ chăm sóc da',
  'Sling Bag': 'Túi đeo chéo',
  'Smart Watch': 'Đồng hồ thông minh',
  'Soft Toy': 'Thú nhồi bông',
  'Stylish T-shirt': 'Áo thun thời trang',
  Sunglasses: 'Kính râm',
  'Wall Art Frame': 'Tranh treo tường',
  Wallet: 'Ví',
  'Wrist Watch': 'Đồng hồ đeo tay',
};
