import { useEffect, useState } from 'react';
import AdminShell from '../components/AdminShell';
import api from '../utils/api';

export default function AdminTaxonomyPage() {
  const [data, setData] = useState({ types: [], labels: [] });
  const [typeForm, setTypeForm] = useState({ code: '', displayName: '' });
  const [labelForm, setLabelForm] = useState({ giftTypeId: '', code: '', displayName: '' });
  const [message, setMessage] = useState('');
  const load = () => api.get('/admin/taxonomy').then(response => setData(response.data)).catch(error => setMessage(error.response?.data?.message || 'Không thể tải taxonomy.'));
  useEffect(load, []);
  const createType = async event => { event.preventDefault(); try { await api.post('/admin/taxonomy/types', typeForm); setTypeForm({ code: '', displayName: '' }); setMessage('Đã tạo loại quà.'); load(); } catch (error) { setMessage(error.response?.data?.message || 'Không thể tạo loại quà.'); } };
  const createLabel = async event => { event.preventDefault(); try { await api.post('/admin/taxonomy/labels', { ...labelForm, giftTypeId: Number(labelForm.giftTypeId) }); setLabelForm({ giftTypeId: '', code: '', displayName: '' }); setMessage('Đã tạo nhãn quà.'); load(); } catch (error) { setMessage(error.response?.data?.message || 'Không thể tạo nhãn quà.'); } };
  const toggle = async (kind, item) => { try { await api.put(`/admin/taxonomy/${kind}/${kind === 'types' ? item.giftTypeId : item.giftLabelId}/active`, { active: !item.active }); load(); } catch (error) { setMessage(error.response?.data?.message || 'Không thể cập nhật taxonomy.'); } };
  const editType = async item => { const displayName = window.prompt('Tên loại quà', item.displayName); if (!displayName) return; const code = window.prompt('Mã loại quà', item.code); if (!code) return; try { await api.put(`/admin/taxonomy/types/${item.giftTypeId}`, { code, displayName }); load(); } catch (error) { setMessage(error.response?.data?.message || 'Không thể sửa loại quà.'); } };
  const editLabel = async item => { const displayName = window.prompt('Tên nhãn quà', item.displayName); if (!displayName) return; const code = window.prompt('Mã nhãn quà', item.code); if (!code) return; try { await api.put(`/admin/taxonomy/labels/${item.giftLabelId}`, { giftTypeId: item.giftTypeId, code, displayName }); load(); } catch (error) { setMessage(error.response?.data?.message || 'Không thể sửa nhãn quà.'); } };
  const input = 'min-w-0 rounded-xl border border-outline-variant px-4 py-3';
  return <AdminShell title="Taxonomy quà tặng">
    <div className="mb-6"><h2 className="text-2xl font-bold">Loại quà và nhãn AI</h2><p className="text-on-surface-variant">Nhãn được ngừng sử dụng thay vì xóa nhằm bảo toàn lịch sử và liên kết sản phẩm.</p></div>
    {message && <p className="mb-4 rounded-xl bg-surface-container px-4 py-3">{message}</p>}
    <div className="grid gap-5 xl:grid-cols-2"><section className="min-w-0 rounded-2xl border border-outline-variant bg-white p-5"><h3 className="text-lg font-bold">Loại quà</h3><form onSubmit={createType} className="mt-4 grid gap-3 sm:grid-cols-[1fr_1.4fr_auto]"><input required placeholder="Mã, ví dụ BOOK" value={typeForm.code} onChange={e => setTypeForm({ ...typeForm, code: e.target.value })} className={input}/><input required placeholder="Tên hiển thị" value={typeForm.displayName} onChange={e => setTypeForm({ ...typeForm, displayName: e.target.value })} className={input}/><button className="rounded-xl bg-primary px-4 py-3 font-bold text-white">Thêm</button></form><div className="mt-5 space-y-2">{data.types.map(type => <div key={type.giftTypeId} className="flex min-w-0 items-center justify-between gap-3 rounded-xl bg-surface-container-low p-3"><div className="min-w-0"><strong className="break-words">{type.displayName}</strong><p className="text-xs text-on-surface-variant">{type.code} · {type.labelCount} nhãn</p></div><div className="flex shrink-0 gap-1"><button onClick={() => editType(type)} className="rounded-full border border-outline-variant px-3 py-1 text-xs font-bold">Sửa</button><button onClick={() => toggle('types', type)} className={`rounded-full px-3 py-1 text-xs font-bold ${type.active ? 'bg-green-100 text-green-800' : 'bg-error-container text-error'}`}>{type.active ? 'Đang dùng' : 'Đã tắt'}</button></div></div>)}</div></section>
    <section className="min-w-0 rounded-2xl border border-outline-variant bg-white p-5"><h3 className="text-lg font-bold">Nhãn quà AI</h3><form onSubmit={createLabel} className="mt-4 grid gap-3"><select required value={labelForm.giftTypeId} onChange={e => setLabelForm({ ...labelForm, giftTypeId: e.target.value })} className={input}><option value="">Chọn loại quà</option>{data.types.filter(type => type.active).map(type => <option key={type.giftTypeId} value={type.giftTypeId}>{type.displayName}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><input required placeholder="Mã nhãn" value={labelForm.code} onChange={e => setLabelForm({ ...labelForm, code: e.target.value })} className={input}/><input required placeholder="Tên nhãn" value={labelForm.displayName} onChange={e => setLabelForm({ ...labelForm, displayName: e.target.value })} className={input}/></div><button className="rounded-xl bg-primary px-4 py-3 font-bold text-white">Thêm nhãn</button></form><div className="mt-5 max-h-[560px] space-y-2 overflow-y-auto pr-1">{data.labels.map(label => <div key={label.giftLabelId} className="flex min-w-0 items-center justify-between gap-3 rounded-xl bg-surface-container-low p-3"><div className="min-w-0"><strong className="break-words">{label.displayName}</strong><p className="text-xs text-on-surface-variant">{label.giftTypeName} · {label.code}</p></div><div className="flex shrink-0 gap-1"><button onClick={() => editLabel(label)} className="rounded-full border border-outline-variant px-3 py-1 text-xs font-bold">Sửa</button><button onClick={() => toggle('labels', label)} className={`rounded-full px-3 py-1 text-xs font-bold ${label.active ? 'bg-green-100 text-green-800' : 'bg-error-container text-error'}`}>{label.active ? 'Đang dùng' : 'Đã tắt'}</button></div></div>)}</div></section></div>
  </AdminShell>;
}
