import { useCallback, useEffect, useState } from 'react';
import StoreShell from '../components/StoreShell';
import api from '../utils/api';

const iso = date => date.toISOString().slice(0, 10);
const fmt = value => value == null ? '—' : Number(value).toLocaleString('vi-VN', { maximumFractionDigits: 1 });
export default function StoreAnalyticsPage() {
  const now = new Date();
  const monthAgo = new Date(); monthAgo.setDate(now.getDate() - 29);
  const [range, setRange] = useState({ from: iso(monthAgo), to: iso(now) });
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  const load = useCallback(async () => { try { const response = await api.get('/store/analytics', { params: range }); setData(response.data); setError(''); } catch (e) { setError(e.response?.data?.message || 'Không thể tải thống kê cửa hàng.'); } }, [range]);
  useEffect(() => { load(); }, [load]);
  const cards = data ? [['Sản phẩm', data.totalProducts], ['Lượt xuất hiện', data.totalAppearances], ['Lượt xem tích lũy', data.totalViews], ['Yêu thích', data.totalFavorites], ['Được lựa chọn', data.totalSelections], ['Điểm trung bình', fmt(data.averageRating)]] : [];
  return <StoreShell title="Thống kê hiệu quả sản phẩm"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold">Hiệu quả cửa hàng</h2><p className="text-on-surface-variant">Lượt xem là số tích lũy; các chỉ số còn lại theo khoảng ngày đã chọn.</p></div><div className="flex flex-wrap gap-2"><label className="text-sm">Từ ngày<input type="date" value={range.from} onChange={e => setRange({ ...range, from: e.target.value })} className="mt-1 block rounded-xl border border-outline-variant px-3 py-2"/></label><label className="text-sm">Đến ngày<input type="date" value={range.to} onChange={e => setRange({ ...range, to: e.target.value })} className="mt-1 block rounded-xl border border-outline-variant px-3 py-2"/></label></div></div>{error && <p className="mb-4 rounded-xl bg-error-container p-4 text-error">{error}</p>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([label, value]) => <div key={label} className="rounded-2xl border border-outline-variant bg-white p-4 shadow-sm"><p className="text-sm text-on-surface-variant">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></div>)}</div>{data && <div className="mt-6 overflow-hidden rounded-2xl border border-outline-variant bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-surface-container"><tr><th className="p-4">Sản phẩm</th><th className="p-4">Trạng thái</th><th className="p-4">Xuất hiện</th><th className="p-4">Lượt xem</th><th className="p-4">Yêu thích</th><th className="p-4">Được chọn</th><th className="p-4">Điểm TB</th></tr></thead><tbody>{data.products.map(product => <tr key={product.productId} className="border-t border-outline-variant"><td className="p-4"><div className="flex items-center gap-3"><div className="h-12 w-12 shrink-0 overflow-hidden rounded-lg bg-surface-container">{product.imageUrl && <img src={product.imageUrl} className="h-full w-full object-cover" alt=""/>}</div><strong className="max-w-[260px] break-words">{product.name}</strong></div></td><td className="p-4 text-sm">{product.status}<br/><span className="text-on-surface-variant">{product.businessStatus}</span></td><td className="p-4">{product.appearances}</td><td className="p-4">{product.views}</td><td className="p-4">{product.favorites}</td><td className="p-4">{product.selections}</td><td className="p-4">{fmt(product.averageRating)}</td></tr>)}</tbody></table></div>{data.products.length === 0 && <p className="p-8 text-center text-on-surface-variant">Cửa hàng chưa có sản phẩm.</p>}</div>}</StoreShell>;
}
